Hw 3
senchov/go_hausaufgaben pull request #2
Opened 2024-08-14 19:24 UTC by senchov

2024-08-15 10:59 UTC, alexandear requested changes

2024-08-15 10:59 UTC, alexandear commented on gocourse03/main.go
> +func moveThroughtCenter(id int, moveTime time.Time, from string, to string) {
Одруківка в назві функції:
```suggestion
func moveThroughCenter(id int, moveTime time.Time, from string, to string) {
```

2024-08-15 10:59 UTC, alexandear commented on gocourse03/main.go
> +const (
Для `RodentType`, `Sector` бажано задекларувати окремий тип, як вказано в завданні домашки.

```go
type RodentType string

type Sector string
```

Таким чином, програма стане надійнішою, тому що не зможемо передати константу `WestSector` у функцію, яка очікує `RodentType`.

2024-08-15 10:59 UTC, alexandear commented on gocourse03/main.go
> +var movements []Movement
Чи можемо обійтися без глобальних змінних? Наприклад, перенести всі ці декларації всередину `main()`.

Звичайно, всі інші функції, які використовують ці змінні, теж треба буде підправити.

2024-08-15 10:59 UTC, alexandear commented on gocourse03/main.go
> +func PrintLocations() {
Пропоную передавати `rodents` та `movements` як параметри функції.

2024-08-16 20:13 UTC, alexandear requested changes
Рухаємось до кращого ;)

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +	NorthSector Sector     = "North"
Між константами різних типів зазвичай додаються пусті рядки для більшої читабельності:
```suggestion
	Hackwrench  RodentType = "Hackwrench"

	NorthSector Sector     = "North"
```

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +	rodents = [4]Rodent{
Чи можемо ми використати тут оператор `:=` замість `=` та прибрати рядок 25 (`var rodents [4]Rodent`)?

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +func GetIndex(arr []Rodent, id int) int {
Думаю, назва функції краща без `Get`, як тут [strings.Index](https://pkg.go.dev/strings#Index).

Назва змінних, пакетів та фукнцій - ціла наука https://go.dev/doc/effective_go#names

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +	northRodents = append(northRodents, rodents[3])
В Go можна оголошувати слайс і відразу присвоювати йому значення. Ось так:

```
numbers := []int{1, 2, 3}
```

Можливо, схожим чином можемо зробити для всіх rodents?

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +	Sector     *[]Rodent
Не можу зрозуміти, чому `Sector` має тип поінтер на слайс. Зазвичай, можна обійтись просто слайсом.

Чи можемо переписати ось так, чи є якась прихована задумка?
```suggestion
	Sector     []Rodent
```

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +func moveThroughtCenter(
Здається, ось так пишеться `through`:
```suggestion
func moveThroughCenter(
```

https://dictionary.cambridge.org/dictionary/english/through

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +func RemoveFromSectorArr(id int, arr []Rodent) *[]Rodent {
Напевно, є сенс перейменувати `arr` -> `rodents`. Бо `[]Rodent` - це слайс `slice`, а не масив `array`.

2024-08-16 20:13 UTC, alexandear commented on gocourse03/main.go
> +	for i := 0; i < len(rodents); i++ {
Може тут краще використати функцію `range`? https://go.dev/tour/moretypes/16

2024-08-17 19:07 UTC, senchov commented on gocourse03/main.go
> +	northRodents = append(northRodents, rodents[3])
через := не вийде бо масив має ссилки в оголошенні rodents 
rodents := [4]Rodent{
		{ID: 1, Sector: &westRodents, RodentType: Chip, FromTo: [2]Sector{WestSector, WestSector}},

2024-08-17 19:10 UTC, senchov commented on gocourse03/main.go
> +	Sector     *[]Rodent
якшо без поінтера то це будуть просто різні слайси, я так і зробив спочатку, яале потім зрозумів шо в мене дані не змінюються

2024-08-18 09:39 UTC, senchov commented on gocourse03/main.go
> +	Sector     *[]Rodent
вирішив взагалі видалити цю ссилку, вона тут посуті не потрібна

2024-08-18 09:42 UTC, senchov commented on gocourse03/main.go
> +	northRodents = append(northRodents, rodents[3])
видалив ссилку на сектор і стало можливо зробити таку правку

2024-08-18 14:45 UTC, alexandear requested changes

2024-08-18 14:45 UTC, alexandear commented on gocourse03/main.go
> +}
Чи потрібна ця функція, якщо нижче вже оголошена аналогічна?
```go
func Index(slice []Rodent, id int) int {
	for i, v := range slice {
		if v.ID == id {
			return i
		}
	}

	return -1
}
```

Нагадаю, що конвертувати з array в slice легко (https://go.dev/blog/slices-intro):

```go
var fourRodents [4]Rodent
rodents := fourRodents[:] // rodents now slice with type []Rodent
```

2024-08-18 14:45 UTC, alexandear commented on gocourse03/main.go
> +func Index(slice []Rodent, id int) int {
Бажано не називати параметри типами. Тобто перейменувати `slice`.

Звідси https://google.github.io/styleguide/go/decisions.html#variable-names

> Omit [types and type-like words](https://google.github.io/styleguide/go/decisions.html#repetitive-with-type) from most variable names

2024-08-18 14:45 UTC, alexandear commented on gocourse03/main.go
> +func moveThroughCenter(
Чи можемо ми створити якусь структуру, в якій зберігатимуться `movements` та `rodents`? Це щоб не передавати купу параметрів туди-сюди.

Якщо у функції понад 5 параметрів - це вже ознака того, що треба подумати про рефакторінг. Ось ця функція приймає цілих 10 аргументів.

2024-08-18 14:45 UTC, alexandear commented on gocourse03/main.go
> +	rodents := [4]Rodent{
Чи потрібен масив для `rodents`? Може просто слайсом обійтися? Це має трішки спростити функції нижче.

2024-08-18 14:45 UTC, alexandear commented on gocourse03/main.go
> +	Center      Sector = "Center"
Може `Center` -> `CenterSector`?

2024-08-18 14:45 UTC, alexandear commented on gocourse03/main.go
> +func SectorSlice(
Думаю, ім'я для функції можна придумати трішки промовистіше. Якщо не дивитись в імплементацію, то незрозуміло, що взагалі робить функція.

2024-08-18 20:09 UTC, senchov commented on gocourse03/main.go
> +func SectorSlice(
раніше був GetSectorSlice але був коментар Get прибрати, тому воно так

2024-08-21 20:15 UTC, alexandear requested changes

2024-08-21 20:15 UTC, alexandear commented on gocourse03/main.go
> +	moveThroughCenter(1, time.Now().Add(10), WestSector, EastSector, param)
`time.Now().Add(10)` - це додати 10 мікросекунд до поточного часу.

Можливо, малось на увазі 10 хвилин? Тоді треба трохи модифікувати:

```
time.Now().Add(10*time.Minutes)
```

2024-08-21 20:15 UTC, alexandear commented on gocourse03/main.go
> +	moveThroughCenter(3, time.Now().Add(13), SouthSector, WestSector, param)
`time.Now()` повторюється 4 рази. Думаю, варто винести в окрему змінну, щоб викликати лише раз.

2024-08-21 20:15 UTC, alexandear commented on gocourse03/main.go
> +func Index(rodentsSlice []Rodent, id int) int {
`Slice` зайвий суфікс:
```suggestion
func Index(rodents []Rodent, id int) int {
```

2024-08-21 20:15 UTC, alexandear commented on gocourse03/main.go
> +func PrintLocations(rodents *[]Rodent, movements *[]Movement) {
Якщо не змінювати слайс через `append`, то не варто використовувати поінтер:

```suggestion
func PrintLocations(rodents []Rodent, movements []Movement) {
```

2024-08-21 20:15 UTC, alexandear commented on gocourse03/main.go
> +type RodentParametr struct {
Помилочка:
```suggestion
type RodentParameter struct {
```

2024-08-21 20:15 UTC, alexandear commented on gocourse03/main.go
> +	PrintLocations(&rodents, &movements)
Спробуй змінити функції `PrintLocations` та `moveThroughCenter`, щоб працювало так:
```suggestion
	var movements []Movement
	PrintLocations(rodents, movements)

	movements = moveThroughCenter(1, time.Now().Add(10), WestSector, EastSector, param, movements)
	movements = moveThroughCenter(2, time.Now().Add(11), EastSector, NorthSector, param, movements)
	movements = moveThroughCenter(2, time.Now().Add(12), NorthSector, SouthSector, param, movements)
	movements = moveThroughCenter(3, time.Now().Add(13), SouthSector, WestSector, param, movements)

	PrintLocations(rodents, movements)
```

Тоді можна видалити буде поле `Movements *[]Movement` з `RodentParameter` і код стане більш ідіоматичним.

2024-08-24 20:52 UTC, alexandear requested changes
Останній штрих.

2024-08-24 20:52 UTC, alexandear commented on gocourse03/main.go
> +	movements = *moveThroughCenter(3, now.Add(13*time.Minute), SouthSector, WestSector, param, &movements)
Ще трохи підправити, щоб без `*` та `&`. Ось так має працювати:
```suggestion
	movements = moveThroughCenter(1, now.Add(10*time.Minute), WestSector, EastSector, param, movements)
	movements = moveThroughCenter(2, now.Add(11*time.Minute), EastSector, NorthSector, param, movements)
	movements = moveThroughCenter(2, now.Add(12*time.Minute), NorthSector, SouthSector, param, movements)
	movements = moveThroughCenter(3, now.Add(13*time.Minute), SouthSector, WestSector, param, movements)
```

2024-08-24 20:52 UTC, alexandear commented on gocourse03/main.go
> +	SouthRodents *[]Rodent
Чим менше зірочок, тим легше читати:
```suggestion
	Rodents      []Rodent
	WestRodents  []Rodent
	EastRodents  []Rodent
	NorthRodents []Rodent
	SouthRodents []Rodent
```

2024-08-24 20:52 UTC, alexandear commented on gocourse03/main.go
> +	southRodents *[]Rodent) *[]Rodent {
Давай всі зірочки видалимо, без них можна обійтись:
```suggestion
	westRodents []Rodent,
	eastRodents []Rodent,
	northRodents []Rodent,
	southRodents []Rodent) []Rodent {
```

2024-08-24 20:52 UTC, alexandear commented on gocourse03/main.go
> +) *[]Movement {
Те саме з зірочками:
```suggestion
	movements []Movement,
) []Movement {
```

2024-09-02 10:42 UTC, alexandear requested changes

2024-09-02 10:42 UTC, alexandear commented on gocourse03/main.go
> +package main
Програма при запуску вилітає з панікою, треба пофіксити:
```
❯ go run main.go
Chip is located in West sector 
Dale is located in East sector 
Cheaser is located in South sector 
Hackwrench is located in North sector 
----------------
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.moveThroughCenter(0x2, {0x1024c5548?, 0x140000a2240?, 0x1021baa40?}, {0x1020f0383, 0x5}, {0x1020f037e, 0x5}, {{0x1400009ae58, 0x4, ...}, ...}, ...)
        /Users/Oleksandr_Redko/src/github.com/senchov/go_hausaufgaben/gocourse03/main.go:87 +0x5d8
main.main()
        /Users/Oleksandr_Redko/src/github.com/senchov/go_hausaufgaben/gocourse03/main.go:53 +0x420
exit status 2
```

2024-09-04 19:14 UTC, senchov commented on gocourse03/main.go
> +package main
Заревертив останній коміт, пробелема була в тому що якщо прибрати поінтери не відбувається сет в слайси в функції moveThroughCenter

2024-09-05 10:19 UTC, alexandear requested changes

2024-09-05 10:19 UTC, alexandear commented on gocourse03/main.go
> +package main
Не потрібно відкочувати останній комміт. Краще переписати код так, щоб без вказівників відбувався сет в слайси та програма працювала.

2024-09-08 15:33 UTC, alexandear approved these changes
LGTM

2024-09-10 17:56 UTC, merged