hw_5
senchov/go_hausaufgaben pull request #4
Opened 2024-08-20 19:53 UTC by senchov

2024-08-21 20:18 UTC, alexandear requested changes
Бажано додати якийсь пакет, відмінний від `main`. Туди помістити всі функції, додати конструктори для кожного типу, поля зробити приватними.

2024-08-25 13:51 UTC, alexandear requested changes

2024-08-25 13:51 UTC, alexandear commented on gocourse05/go.mod
> +go 1.22.6
Варто використовувати найновішу версію go 1.23.0
```suggestion
go 1.23.0
```

2024-08-25 13:51 UTC, alexandear commented on gocourse05/main.go
> +
Зайвий рядок. Можна налаштувати собі `gofumpt` для автоматичного форматування.

Писав про це в Slack https://golang-beginning-6.slack.com/archives/C07EVP8S4FK/p1724071944955179

---
Не забувайте видаляти непотрібні пусті рядки, як ось тут:

```
func sum(a, b int) int {

	return a + b
}
```
`gofmt` таке пропускає, а я - ні. В реальних проектах на десятки тисяч рядків, зайвих рядків може бути тисячу, а це вже немало. Наприклад, ось мій PR, де видалялись непотрібні рядки, його без проблем прийняли.

Щоб полегшити собі життя, варто поставити gofumpt [mvdan/gofumpt](https://github.com/mvdan/gofumpt). Цей тул є надбудовою над gofmt: видаляє непотрібні пусті рядки, сортує імпорти тощо. В README вказано точніше, що програма вміє робити.

Поставити такою командою:
```
go install mvdan.cc/gofumpt@latest
```
Щоб відформатувати всі файли:
```
gofumpt -w .
```
Також можна запускати ось так, якщо з якоїсь причини не працює попередня команда:
```
go run mvdan.cc/gofumpt@latest -w .
```

2024-08-25 13:51 UTC, alexandear commented on gocourse05/security/security.go
> +	Angle float32
Давай зробимо інкапсуляцію цих полей:
```suggestion
	range float32
	angle float32
```

2024-08-25 13:51 UTC, alexandear commented on gocourse05/security/security.go
> +	Angle float32
Для `FixedCamera` також.

2024-08-25 13:51 UTC, alexandear commented on gocourse05/security/security_test.go
> +		t.Error("PTZ camera dosen't rotate")
помилочка:
```suggestion
		t.Error("PTZ camera doesn't rotate")
```

2024-08-25 13:51 UTC, alexandear commented on gocourse05/security/security_test.go
> +		t.Error("Fixed camera shouldnt rotate")
помилочка
```suggestion
		t.Error("Fixed camera shouldn't rotate")
```

2024-08-25 13:51 UTC, alexandear commented on gocourse05/security/security_test.go
> +		t.Error("Doesen't record anything")
```suggestion
		t.Error("Doesn't record anything")
```

2024-08-25 13:51 UTC, alexandear commented on gocourse05/security/security.go
> +type Rotater interface {
📝 круто, що ти запам'ятав про суфікс `-er` для інтерфейсів, у яких один метод.

2024-08-25 13:51 UTC, alexandear commented on gocourse05/main.go
Програма має виводити щось корисне.

Зараз так:

```sh
❯ go run main.go
[]
{Tiger Walking}
{Tiger Walking}
```

Можемо покращити?

---

Ось коментар щодо домашки від автора курсу, який придумав це завдання:

<img width="830" alt="image" src="https://github.com/user-attachments/assets/2abcba4e-e97f-4d1c-96fe-bdb7791ade0f">

2024-08-25 13:51 UTC, alexandear commented on gocourse05/main.go
> +	nv := security.NewNightvisionCamera(30, 6)
Чи можемо використати інтерфейси?

Наприклад, оголосити слайс рекордерів `security.Recorder`, і в циклі для кожної камери викликати метод "Record".

Те ж саме для `security.Rotater`.

2024-08-25 13:51 UTC, alexandear commented on gocourse05/go.mod
> +go 1.22.6
https://go.dev/dl/

2024-08-31 17:43 UTC, senchov commented on gocourse05/main.go
> +
шото не заканало, пофіксив руцями
`andreysenchov@Andreys-MacBook-Pro gocourse05 % go install mvdan.cc/gofumpt@latest
go: downloading mvdan.cc/gofumpt v0.7.0
go: downloading golang.org/x/sync v0.6.0
go: downloading golang.org/x/tools v0.17.0
go: downloading golang.org/x/mod v0.14.0
andreysenchov@Andreys-MacBook-Pro gocourse05 % gofumpt -w .
zsh: command not found: gofumpt
andreysenchov@Andreys-MacBook-Pro gocourse05 % go install mvdan.cc/gofumpt@latest
andreysenchov@Andreys-MacBook-Pro gocourse05 % gofumpt -help
zsh: command not found: gofumpt
andreysenchov@Andreys-MacBook-Pro gocourse05 % gofumpt -help
zsh: command not found: gofumpt
`

2024-08-31 18:11 UTC, senchov commented on gocourse05/main.go
добавив кейсів

2024-09-02 13:31 UTC, alexandear requested changes

2024-09-02 13:31 UTC, alexandear commented on gocourse05/main.go
Уяви, що незнайома людина запускає твою програму. Бачить це:

```
❯ go run main.go
[]
{Bear Sleep}
{Tiger Walking}
{Rat Eat}
{Tiger Walking}
{Rat Walking}
{Bear Sleep}
{Rat Eat}
{Bear Eat}
{Bear Sleep}
{Tiger Walking}
{Rat Eat}
{Tiger Walking}
{Rat Walking}
{Bear Sleep}
{Rat Eat}
{Bear Eat}
...
```

Вона зрозуміє хоча б приблизно з виводу програми, що відбувається?

2024-09-02 13:31 UTC, alexandear commented on gocourse05/security/security.go
> +type Conditions struct {
Краще без суфіксу `s`:
```suggestion
type Condition struct {
```

Зазвичай із суфіксом `s` пишуть колекцію типів.

2024-09-02 13:31 UTC, alexandear commented on gocourse05/security/security.go
> +}
Пропоную ось ці два інтерфейси перемістити в `main.go`. Все має працювати.

Ось тут пояснення: https://go.dev/wiki/CodeReviewComments#interfaces

В наступних заняттях буде розглянуто детальніше.

2024-09-02 13:31 UTC, alexandear commented on gocourse05/security/security.go
> +func (ptz *PTZCamera) Record(c Conditions, records *[]AnimalRecord, rec AnimalRecord) {
Ось такий паттерн для додавання в слайс:
```suggestion
func (ptz *PTZCamera) Record(c Conditions, records []AnimalRecord, rec AnimalRecord) []AnimalRecord {
```

Ось як тут https://go.dev/wiki/SliceTricks#move-to-front-or-prepend-if-not-present-in-place-if-possible

2024-09-02 13:31 UTC, alexandear commented on gocourse05/security/security.go
> +func (ptz *FixedCamera) Rotate(angle float32) {
Пропоную ось так відрефакторити, це явно дасть знати, чому `angle` ігнорується:
```suggestion
func (ptz *FixedCamera) Rotate(_ float32) {
```

2024-09-05 18:16 UTC, alexandear requested changes

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +func NewConditions(isNight bool, dst Range, battery int) *Condition {
Зайвий `s` префікс, здається. Також не дуже добре виглядає, коли одне слово в рядку скорочене, а всі інші - ні. Пропоную так:
```suggestion
func NewCondition(isNight bool, distToAnimal Range, battery int) *Condition {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +)
Думаю, ці типи та константи гарно будуть дивитись в пакеті `animal`.

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security_test.go
> +func TestRotate(t *testing.T) {
Пропоную розбити цей тест на два:

1. `TestPTZCamera_Rotate`
2. `TestFixedCamera_Rotate`

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security_test.go
> +func TestRecord(t *testing.T) {
Пропоную розбити цей тест на два:

1. `TestPTZCamera_Record`
2. `TestFixedCamera_Record`

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security_test.go
> +		t.Error("PTZ camera doesn't rotate")
Думаю, можна покращити меседж. Ось тут є приклади https://go.dev/wiki/CodeReviewComments#useful-test-failures

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security_test.go
> +		t.Error("Shouldn't record at night")
Думаю, можна покращити меседж. Ось тут є приклади https://go.dev/wiki/CodeReviewComments#useful-test-failures

2024-09-05 18:16 UTC, alexandear commented on gocourse05/main.go
> +	for i := 0; i < 100; i++ {
Можна спростити:
```suggestion
	for range 100 {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/main.go
> +		for j := 0; j < 2; j++ {
Пропоную спростити:
```suggestion
		for j := range 2 {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +func (ptz *PTZCamera) Record(c Condition, records []AnimalRecord, rec AnimalRecord) []AnimalRecord {
Краще тут повністю параметри:
```suggestion
func (ptz *PTZCamera) Record(condition Condition, records []AnimalRecord, record AnimalRecord) []AnimalRecord {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +func (nv *NightvisionCamera) Record(c Condition, records []AnimalRecord, rec AnimalRecord) []AnimalRecord {
Краще тут повністю параметри:
```suggestion
func (nv *NightvisionCamera) Record(c Condition, records []AnimalRecord, rec AnimalRecord) []AnimalRecord {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +func NewNightvisionCamera(r Range, a Angle) *NightvisionCamera {
Не економимо на буквах))
```suggestion
func NewNightvisionCamera(range Range, angle Angle) *NightvisionCamera {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +func NewFixedCamera(r Range, a Angle) *FixedCamera {
```suggestion
func NewFixedCamera(range Range, angle Angle) *FixedCamera {
```

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +	Angle
Пропоную взагалі видалити `Angle`, бо для `FixedCamera` це поле завжди 0.

2024-09-05 18:16 UTC, alexandear commented on gocourse05/security/security.go
> +type FixedCamera struct {
Здається, в `main.go` ніде не використовується ця структура. Лише в тестах. А має.

2024-09-18 17:47 UTC, alexandear approved these changes
LGTM

2024-09-18 17:48 UTC, alexandear commented on gocourse05/main.go
> +
Можна `go run mvdan.cc/gofumpt@latest -w .`

2024-09-19 17:42 UTC, merged