Hw 6
senchov/go_hausaufgaben pull request #5
Opened 2024-08-24 19:49 UTC by senchov

2024-08-27 20:09 UTC, alexandear requested changes
Не все з домашнього завдання реалізовано. Можеш переглянути та доробити?

<img width="718" alt="image" src="https://github.com/user-attachments/assets/f052b30d-88a6-428b-99bd-f5890fc29def">

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main.go
> +// (наприклад, рівень здоров'я, голод, настрій) і відправляє їх через канал до центральної системи моніторингу.
Ось це було в умові задачі. Але бачу, що в `main()` лише одна горутина створена.

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +		t.Logf("Dave data is 0 expexted more than zero")
[`t.Logf`](https://pkg.go.dev/testing#T.Logf) не фейлить тест. Варто використовувати [`t.Errorf`](https://pkg.go.dev/testing#T.Errorf)

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +	fmt.Println(daveStr)
Для тестів замість `fmt.Println` варто використовувати `t.Logf`.

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +	fmt.Println(daveStr)
Комент стосується до всього файлу.

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +		t.Logf("Dave data is 0 expexted more than zero")
Комент стосується до всього файлу.

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +		t.Logf("Mike data is 0 expexted more than zero")
```suggestion
		t.Logf("Mike data is 0 expected more than zero")
```

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +		t.Logf("Mike data is 0 expexted more than zero")
Комент стосується до всього файлу.

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +	fullIds := []int{
```suggestion
	fullIDs := []int{
```

https://go.dev/wiki/CodeReviewComments#initialisms

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +	emptyIds := []int{
```suggestion
	emptyIDs := []int{
```

https://go.dev/wiki/CodeReviewComments#initialisms

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main_test.go
> +		t.Error("Second cage should be closed but it oepned")
```suggestion
		t.Error("Second cage should be closed but it opened")
```

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main.go
> +func CheckTrough(t Trough, full chan int, empty chan int) {
Чи можемо додати стрілочки до каналів?

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main.go
> +func IsShouldOpenCage(hour int, data chan bool) {
Чи можемо додати стрілочку до каналу?

2024-08-27 20:09 UTC, alexandear commented on gocourse06/main.go
> +func CollectData(a Animal, data chan string) {
Чи можемо додати стрілочку до каналу?

2024-09-01 07:37 UTC, senchov commented
> Не все з домашнього завдання реалізовано. Можеш переглянути та доробити?
> 
> <img alt="image" width="718" src="https://private-user-images.githubusercontent.com/3228886/361957945-f052b30d-88a6-428b-99bd-f5890fc29def.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzM5NzcsIm5iZiI6MTcyNTE3MzY3NywicGF0aCI6Ii8zMjI4ODg2LzM2MTk1Nzk0NS1mMDUyYjMwZC04OGE2LTQyOGItOTliZC1mNTg5MGZjMjlkZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDFUMDY1NDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY1ZDlmZWRkZTAxZDk4Zjk3Njc0OWQyMDNkYTIzODAyYzk2NDc3ZTY5ZDk1NGE4MDFkNDlmYzFjZTNjMGFiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hIfcqY2J37meDHXH0xMKRwe5lRFCrJ5ZFDZr-EHzkFQ">

Реализував згідно ТЗ, там є коментарі які показують шо де реалізовано 
<img width="832" alt="image" src="https://github.com/user-attachments/assets/3993b231-a3a0-452d-9455-13628158431a">
<img width="924" alt="image" src="https://github.com/user-attachments/assets/380770cd-5174-475d-b532-94e5a9735ffb">

2024-09-01 08:04 UTC, senchov commented on gocourse06/main.go
> +// (наприклад, рівень здоров'я, голод, настрій) і відправляє їх через канал до центральної системи моніторингу.
добави декілька

2024-09-03 09:48 UTC, alexandear commented on gocourse06/main_test.go
> +	fmt.Println(daveStr)
```suggestion
	t.Log(daveStr)
```

2024-09-03 14:52 UTC, alexandear requested changes

2024-09-03 14:52 UTC, alexandear commented on gocourse06/main.go
> +	go CollectData(Animal{Mood: Sad, Hunger: 0, Health: 56}, undefinedData)
Пропоную використати для синхронізації горутин [`sync.WaitGroup`](https://pkg.go.dev/sync#WaitGroup), щоб попрактикуватись.

В допомогу https://leangaurav.medium.com/common-mistakes-when-using-golangs-sync-waitgroup-88188556ca54

2024-09-08 14:59 UTC, alexandear approved these changes
LGTM

2024-09-08 14:59 UTC, alexandear commented on gocourse06/main.go
> +	go CollectData(Animal{Mood: Sad, Hunger: 0, Health: 56}, &wg)
Пропущена ініціалізація поля `Animal.Name`.

2024-09-08 14:59 UTC, alexandear commented on gocourse06/main.go
> +
📝  Зайвий порожній рядок.

2024-09-08 14:59 UTC, alexandear commented on gocourse06/main.go
> +
📝 Зайвий порожній рядок

2024-09-10 17:57 UTC, merged