hw 8
senchov/go_hausaufgaben pull request #6
Opened 2024-09-08 09:44 UTC by senchov

2024-09-08 16:42 UTC, alexandear requested changes

2024-09-08 16:42 UTC, alexandear commented on gocourse08/main.go
> +	"math/rand"
```suggestion
	"math/rand/v2"
```

Ось тут почитати, чому так https://go.dev/blog/randv2

2024-09-08 16:42 UTC, alexandear commented on gocourse08/main.go
> +	Temparature int
Одруківка:
```suggestion
	Temperature int
```

2024-09-08 16:42 UTC, alexandear commented on gocourse08/main.go
> +	Dexeterity float32
Одруківка:
```suggestion
	Dexterity float32
```

2024-09-08 16:42 UTC, alexandear commented on gocourse08/main.go
> +package main
В домашці бути "Generics"

- https://go.dev/tour/generics/1
- https://tour.ardanlabs.com/tour/eng/generics-basics/1

2024-09-08 16:42 UTC, alexandear commented on gocourse08/main.go
> +		Subgect:   animal,
Одруківка:
```suggestion
		Subject:   animal,
```

2024-09-18 16:55 UTC, senchov commented on gocourse08/main.go
> +package main
ну так є 
<img width="422" alt="image" src="https://github.com/user-attachments/assets/0cb6d769-027b-4cd3-9022-5bc5ce515de7">

2024-09-18 17:51 UTC, alexandear approved these changes
LGTM

2024-09-18 17:51 UTC, alexandear commented on gocourse08/api.wsd
> +class op{
Випадково закомічений файл?

2024-09-18 17:51 UTC, alexandear commented on gocourse08/main.go
> +package main
Вибач, не побачив.

2024-09-18 17:53 UTC, alexandear commented on gocourse08/main.go
> +	intensity := rand.Int32N(100)
Простіше:
```suggestion
	intensity := rand.IntN(100)
```

2024-09-18 17:53 UTC, alexandear commented on gocourse08/main.go
> +	index := int(rand.Int32N(int32(len(sounds))))
Значно простіше:
```suggestion
	index := rand.N(len(sounds))
```

2024-09-19 17:41 UTC, merged